# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/warp2/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/zte/warp2/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    vendor/zte/warp2/proprietary/lib/libnv.so:obj/lib/libnv.so \
    vendor/zte/warp2/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/zte/warp2/proprietary/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \
    vendor/zte/warp2/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/warp2/proprietary/bin/rild:system/bin/rild \
    vendor/zte/warp2/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/zte/warp2/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/warp2/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/zte/warp2/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/zte/warp2/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/warp2/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/zte/warp2/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/warp2/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/zte/warp2/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/zte/warp2/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/zte/warp2/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/zte/warp2/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/zte/warp2/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/zte/warp2/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/warp2/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/warp2/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/zte/warp2/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/warp2/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/warp2/proprietary/lib/libpdapi.so:system/lib/libpdapi.so \
    vendor/zte/warp2/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/zte/warp2/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/zte/warp2/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/zte/warp2/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/zte/warp2/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/warp2/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/zte/warp2/proprietary/lib/libpdsm_atl.so:system/lib/libpdsm_atl.so \
    vendor/zte/warp2/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/zte/warp2/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/zte/warp2/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/zte/warp2/proprietary/lib/libuim.so:system/lib/libuim.so \
    vendor/zte/warp2/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/zte/warp2/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/zte/warp2/proprietary/lib/librpc.so:system/lib/librpc.so \
    vendor/zte/warp2/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/zte/warp2/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/zte/warp2/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/zte/warp2/proprietary/bin/thermald:system/bin/thermald \
    vendor/zte/warp2/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/zte/warp2/proprietary/etc/thermald.conf:system/etc/thermald.conf \
    vendor/zte/warp2/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/zte/warp2/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/zte/warp2/proprietary/lib/libv8.so:system/lib/libv8.so
